version: '3.8'
services:
  # DATABAS
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d 

        # BACKEND
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile  
    container_name: backend_container
    restart: always
    environment:
      DB_HOST: postgres 
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: supersecretpassword
      DB_NAME: postgresdb
    ports:
      - "80:3000"  
    depends_on:
      - postgres  

volumes:
  postgres_data:
